### ISSUE TITLE
Add a way to access the 18F Guides home page from each guide

### ISSUE THREAD

**Issue by jenniferthibault** [18F/archived-guides#12]
People who are reading one guide might not know that we have other handy documents on different topics. It would be nice to have a away back to the main guide list page (https://pages.18f.gov/guides/) from any interior page of any guide, but certainly from the landing page for each guide (https://pages.18f.gov/agile/ https://pages.18f.gov/content-guide/ etc).

Perhaps it could go either in the footer, or up top under the blue header line?

The style should probably be the same as for the team page:

![screen shot 2015-07-09 at 10 52 45 am](https://cloud.githubusercontent.com/assets/11636908/8598432/b665e9e2-2628-11e5-8180-b8ccba6e71c5.png)

**Comment by mbland** [comment]
I'm totally open to that. Mind posting this issue to [18F/guides-template](https://github.com/18F/guides-template) instead, though?

**Comment by jenniferthibault** [comment]
Will do! Sorry, I followed the GitHub link here from the main guide page.
