### ISSUE TITLE
Guides are not continuously deployed

### ISSUE THREAD

**Issue by jeremiak** [18F/archived-guides#39]
Even though @ccostino merged #37 to the `18f-pages` branch, the guides at [pages.18f.gov/guides](https://pages.18f.gov/guides) isn't updated to reflect those changes. I took a look at the webhooks and it doesn't seem like there is anything for the pages.18f.gov

**Comment by ccostino** [comment]
@jeremiak, I think they are, @wslack noticed an error in the build logs before.  PR #41 appears to have fixed the issue, and the guides are now being rebuilt automatically again.

https://github.com/18F/pages-server appears to be where these hooks are handled for when changes are merged according to @wslack.

Going to close this issue for now, but if something crops up again in the future please feel free to re-open!

**Comment by wslack** [comment]
I can confirm; _no webhook set-up is needed_ to make 18f-pages branches work for any repo in the 18F org. I cannot, however, cite where Mike told me that.

**Comment by ccostino** [comment]
Thanks, @wslack!  I pinged #hub in Slack to let them know so others are aware. :-)
