### ISSUE TITLE
Front end guide nav text gets highlighted inappropriately

### ISSUE THREAD

**Issue by nkkl** [18F/archived-guides#44]
The highlight is inconsistent with what section has been selected, doesn't match the rest of the guide nav behavior, and has poor contrast.

![screen shot 2016-08-12 at 10 12 55 am 2](https://cloud.githubusercontent.com/assets/766654/17630773/9fb7340c-6075-11e6-8fa3-1188e24e500a.png)

**Comment by jseppi** [comment]
This appears to no longer be an issue with https://frontend.18f.gov/

<img width="352" alt="screen shot 2017-05-22 at 11 15 10 am" src="https://cloud.githubusercontent.com/assets/697848/26318202/fecfc15e-3edf-11e7-8ef1-ff4e770c3061.png">
