### ISSUE TITLE
Change guides.18f.gov to the guides directory

### ISSUE THREAD

**Issue by wslack** [18F/archived-guides#51]
Steps:

1. ~Better understand how the current CDN route is configured~. (done, answer is "" for path)
2. ~Guides is building on GovCloud~ (done)
3. Update route pages.18f.gov to exclude guides.18f.gov: `cf update-service pages.18f.gov -c '{"domain": "pages.18f.gov", "origin": "federalist-redirect.app.cloud.gov", "path": ""}'`
4. Merge https://github.com/18F/pages-redirects/pull/69
5. Delete current guides CNAME from https://github.com/18F/dns/blob/deploy/terraform/18f.gov.tf 
6.  After the domain is freed, run a command to make a new route: `cf create-service cdn-route cdn-route guides.18f.gov-route -c '{"domain": "guides.18f.gov", "origin": "federalist-proxy.app.cloud.gov", "path": "/site/18f/guides"}'`
7. Retrieve cloudfront URL
8. Add entry in https://github.com/18F/dns/blob/deploy/terraform/18f.gov.tf 

```
resource "aws_route53_record" "18f_gov_guides_18f_gov_a" {
  zone_id = "${aws_route53_zone.18f_gov_zone.zone_id}"
  name = "guides.18f.gov."
  type = "A"
  alias {
    name = "CDN-Broker-makes-this.cloudfront.net."
    zone_id = "Z2FDTNDATAQYW2"
    evaluate_target_health = false
  }
}
```

Revert plan:

- Revert https://github.com/18F/pages-redirects/pull/69
- restore previous CDN setting
- restore DNS CNAME

**Comment by wslack** [comment]
Need to confirm this looks right.

**Comment by LinuxBozo** [comment]
@wslack The current path for `pages.18f.gov` CDN service instance is the default: `""`

**Comment by wslack** [comment]
updated! @ccostino once you verify this looks ok we can execute.

**Comment by ccostino** [comment]
I think this is okay and should be good to go.  Nice to see the revert plan just in case, too. :-)  Thanks, @wslack!

**Comment by wslack** [comment]
Just realized my PR to the pages-redirects app needs a review first!

**Comment by ccostino** [comment]
That's the https://github.com/18F/pages-redirects/pull/69 PR, right @wslack?

**Comment by jmhooper** [comment]
I gave this a 👀 as well. :+1: from me!

**Comment by wslack** [comment]
Sorry all, one more thing I don't understand. When I run `cf service pages.18f.gov` in the `redirects` space, I see ```Service instance provisioned [pages.18f.gov,guides.18f.gov => federalist-redirect.app.cloud.gov]```

But pages.18f.gov is linked to pages-redirects already....so is the mapping in the space overriding the CDN setting?

**Comment by jmhooper** [comment]
I'd think it would be the opposite. I'd _think_ whatever is configured in the DNS repo will take precedence, and right now the DNS repo points both `pages.18f.gov` and `guides.18f.gov` to the same CloudFront instance. I'd imagine that's this `pages.18f.gov` service.

**Comment by wslack** [comment]
So the DNS repo is pointed to this CloudFrong route, and this cloudfront route is pointed at federalist-redirect.app.cloud.gov......so what is pointed at pages-redirects.app.cloud.gov?

**Comment by wslack** [comment]
I think the routes are bound in a way that overrides the config. I don't think my command will impact that, but I'm not 100% sure.

**Comment by wslack** [comment]
New command `cf update-service pages.18f.gov -c '{"domain": "pages.18f.gov", "origin": "pages-redirects.app.cloud.gov", "path": ""}'`

**Comment by wslack** [comment]
Completed through step 5 right now, waiting for domain to be available for step 6.

**Comment by wslack** [comment]
Got domain, just filed new DNS record

**Comment by wslack** [comment]
This is done! We forgot to update the menu links, which https://github.com/18F/guides/pull/52 took care of.
